# Shared rule producing cuda/cuda-protocol-hash.h, the truncated SHA-256
# of the cuda-packet-manager source files used as a non-cryptographic
# compatibility tag in the gdb/gdbserver remote protocol handshake.
#
# Included by both gdb/Makefile.in and gdbserver/Makefile.in (the same way
# both include silent-rules.mk).  The includer must define the variables
# srcdir, SHELL, SILENCE, and SHA256SUM.  No per-side configuration is
# required: the manifest below references each contributing file via
# $(srcdir)/.. (which resolves to the parent cuda-gdb/ directory from
# either Makefile's srcdir), so both sides see the same byte stream and
# produce identical hashes by construction.
#
# To extend protocol coverage to additional files, add them to
# CUDA_PROTOCOL_HASH_SOURCES below.  No other Makefile changes are
# required.

CUDA_PROTOCOL_HASH_SOURCES = \
	$(srcdir)/../gdb/cuda/cuda-packet-manager.h \
	$(srcdir)/../gdb/cuda/cuda-packet-manager.c \
	$(srcdir)/../gdb/cuda/cuda-packet-format.h \
	$(srcdir)/../gdbserver/cuda/cuda-packet-manager.cc

cuda/cuda-protocol-hash.h: stamp-cuda-protocol-hash; @true
stamp-cuda-protocol-hash: $(CUDA_PROTOCOL_HASH_SOURCES) Makefile
	@echo "  GEN    cuda/cuda-protocol-hash.h"
	$(SILENCE) [ -d cuda ] || mkdir -p cuda
	$(SILENCE) hash=`cat $(CUDA_PROTOCOL_HASH_SOURCES) \
	                 | $(SHA256SUM) | cut -c1-16`; \
	  ( echo '/* Generated by Makefile.  Do not edit.  */'; \
	    echo '#ifndef CUDA_PROTOCOL_HASH_H'; \
	    echo '#define CUDA_PROTOCOL_HASH_H 1'; \
	    echo '/* Truncated (64-bit) SHA-256 of the cuda-packet-manager'; \
	    echo '   source files.  Used as a non-cryptographic compatibility'; \
	    echo '   tag in the gdb/gdbserver remote protocol handshake.  */'; \
	    echo "#define CUDA_PROTOCOL_HASH \"$$hash\""; \
	    echo '#endif' ) > cuda-protocol-hash.tmp
	$(SILENCE) $(SHELL) $(srcdir)/../move-if-change \
	    cuda-protocol-hash.tmp cuda/cuda-protocol-hash.h
	$(SILENCE) echo stamp > stamp-cuda-protocol-hash

CUDA_PROTOCOL_HASH_INCLUDERS = \
	cuda/cuda-packet-manager.o \
	remote.o \
	server.o

$(CUDA_PROTOCOL_HASH_INCLUDERS): cuda/cuda-protocol-hash.h
