load_lib dwarf.exp
require dwarf2_support
standard_testfile .c .S

lassign [function_range main $srcdir/$subdir/$srcfile] \
    main_addr main_len
lassign [function_range func1 $srcdir/$subdir/$srcfile] \
    func1_addr func1_len
lassign [function_range func2 $srcdir/$subdir/$srcfile] \
    func2_addr func2_len

set asm_file [standard_output_file $srcfile2]
Dwarf::assemble $asm_file {
    upvar cu_lang cu_lang
    set cu_version 4
    global func1_addr func1_len
    global func2_addr func2_len
    global main_addr main_len
    set buffer_src [gdb_target_symbol buffer]

    cu { version $cu_version } {
	declare_labels uinteger_label bool_label struct_label
	declare_labels foo_location_list discr_label

	DW_TAG_compile_unit {
            {DW_AT_language @DW_LANG_C_plus_plus}
	} {
            uinteger_label: DW_TAG_base_type {
                {DW_AT_byte_size 4 DW_FORM_sdata}
                {DW_AT_encoding  @DW_ATE_unsigned}
                {DW_AT_name      {unsigned int}}
            }

            bool_label: DW_TAG_base_type {
                {DW_AT_byte_size 1 DW_FORM_sdata}
                {DW_AT_encoding  @DW_ATE_boolean}
                {DW_AT_name      {bool}}
            }

	   struct_label: DW_TAG_structure_type {
		{DW_AT_name {test}}
		{DW_AT_byte_size 8 DW_FORM_sdata}
	    } {
		discr_label: DW_TAG_member {
		    {DW_AT_type :$uinteger_label}
                    {DW_AT_name      {disc}}
		    {DW_AT_data_member_location 0 data1}
		    {DW_AT_artificial 1 DW_FORM_flag}
		}

		DW_TAG_variant_part {
		    {discr :$discr_label DW_FORM_ref4}
		} {
		    DW_TAG_variant {
			{DW_AT_discr_value 0 sdata}
		    } {
			DW_TAG_member {
			    {DW_AT_type :$uinteger_label}
                            {DW_AT_name      {unsigned_member}}
			    {DW_AT_data_member_location 4 data1}
			}
		    }

		    DW_TAG_variant {
                        {DW_AT_discr_value 1 sdata}
		    } {
			DW_TAG_member {
			    {DW_AT_type :$bool_label}
                            {DW_AT_name      {bool_member}}
			    {DW_AT_data_member_location 4 data1}
			}
		    }
		}
	    }

	    DW_TAG_variable {
		{DW_AT_name "foo"}
		{DW_AT_location $foo_location_list DW_FORM_sec_offset}
		{DW_AT_type :$struct_label}
	    }

	    DW_TAG_variable {
		{DW_AT_name "bar"}
		{DW_AT_location {
		    DW_OP_addr $buffer_src
		} SPECIAL_expr}
		{DW_AT_type :$struct_label}
	    }

	    DW_TAG_variable {
		{DW_AT_name "bar_discr"}
		{DW_AT_location {
		    DW_OP_addr $buffer_src
		} SPECIAL_expr}
		{DW_AT_type :$uinteger_label}
	    }

	    DW_TAG_subprogram {
	        {DW_AT_name "func1"}
	        {DW_AT_low_pc $func1_addr}
	        {DW_AT_high_pc $func1_len DW_FORM_udata}
	    }

	    DW_TAG_subprogram {
		{DW_AT_name "func2"}
		{DW_AT_low_pc $func2_addr}
		{DW_AT_high_pc $func2_len DW_FORM_udata}
   	    }

	    DW_TAG_subprogram {
		{DW_AT_name "main"}
		{DW_AT_low_pc $main_addr}
		{DW_AT_high_pc $main_len DW_FORM_udata}
   	    }
	}
    }

    # Generate a .debug_loc contribution.
    loc { cu_version $cu_version } {
	foo_location_list:
	entry $main_addr "$main_addr + $main_len" {
	    DW_OP_consts 1
	    DW_OP_stack_value
            DW_OP_piece 4
            DW_OP_consts 1
	    DW_OP_stack_value
            DW_OP_piece 4
	}
	entry $func1_addr "$func1_addr + $func1_len" {
	    DW_OP_consts 0
	    DW_OP_stack_value
            DW_OP_piece 4
            DW_OP_consts 30
	    DW_OP_stack_value
            DW_OP_piece 4
	}
	entry $func2_addr "$func2_addr + $func2_len" {
	    DW_OP_consts 1
	    DW_OP_stack_value
            DW_OP_piece 4
            DW_OP_consts 1
	    DW_OP_stack_value
            DW_OP_piece 4
	}
    }
}

if { [prepare_for_testing ${testfile}.exp ${testfile} \
     [list $srcfile $asm_file] debug] } {
    return -1
}

if ![runto_main] {
    return -1
}

with_test_prefix "at main" {
    gdb_test "print foo" " = true"
    gdb_test "print bar" " = 2"
}

gdb_breakpoint "func1"
gdb_breakpoint "func2"

gdb_continue_to_breakpoint "func1"
with_test_prefix "at func1" {
    gdb_test_no_output "set variable bar = 1"
    gdb_test_no_output "set variable bar_discr = 1"
    gdb_test "print foo" " = 30"
    gdb_test "print bar" " = true"
}

gdb_continue_to_breakpoint "func2"
with_test_prefix "at func2" {
    gdb_test_no_output "set variable bar_discr = 0"
    gdb_test "print foo" " = true"
    gdb_test "print bar" " = 1"
}
