# NVIDIA CUDA Debugger CUDA-GDB
# Copyright (C) 2007-2025 NVIDIA Corporation
# Written by CUDA-GDB team at NVIDIA <cudatools@nvidia.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# This is a board to run tests with cuda-gdb

set_board_info gdb_prompt "\\(cuda-gdb\\)"
set_board_info compiler "[find_gcc]"
load_board_description "local-board"
